import 'package:get/get.dart';

class MyLocal extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'ar': {
          'Sign In': 'تسجيل الدخول',
          'Promotional text': 'نص ترويجي',
          'Send Code': 'ارسال الرمز',
          'New Account': 'حساب جديد',
          'Guest': 'تسجيل سريع',
          'Register': 'انشاء حساب',
          'Forget Password': 'نسيت كلمة المرور',
          'Verified': 'التحقق',
          'Full Name': 'اسم كامل',
          'Gmail': 'جيميل',
          'Password': 'كلمة المرور',
          'Mobile': 'رقم الجوال',
          'Agree to privacy and terms': 'الموافقة على و الشروط الخصوصية',
          'Chats': 'الرسائل',
          'Typing': 'مراسلة',
          'Offers': 'العروض المقدمة',
          'ID': 'رقم الموظف',
          'Offer Details': 'تفاصيل الطلب',
          'Vehicle Location': 'موقع السطحة',
          'From': 'الإنطلاق',
          'To': 'الانزال',
          'SAR': 'ر.س',
          'Send Offer': 'قدم عرض',
          'Accepting Offer': 'قبول العرض',
          'Delivery Price': 'حق التوصيل',
          'Vehicle Order': 'اطلب السطحة',
          'Service Price': 'رسوم الخدمة',
          'Request completed successfully': 'تم الطلب بنجاح',
          'search on a vehicle in the area': 'البحث على سطحة في المنطقة',
          'Current Password': 'كلمة مرور القديمة',
          'Create New Password': 'انشاء كلمة مرور جديدة',
          'New Password': 'كلمة مرور جديدة',
          'Password Confirmation': 'تأكيد كلمة المرور',
          'Update': 'تحديث',
          'Update Information': 'تعديل بياناتي',
          'Save': 'حفظ',
          'Favorite': 'المفضلة',
          'Help': 'طلب المساعدة',
          'Write what help you need': 'اكتب ما تريده من مساعدة',
          'Common Questions': 'الأسئلة الشائعة',
          'Send': 'أرسل',
          'Wallet': 'المحفظة',
          'Share': 'مشاركة',
          'Change Password': 'تغيير كلمة المرور',
          'Setting': 'الإعدادات',
          'Coupon': 'الكوبون',
          'Terms and Conditions': 'الشروط و الأحكام',
          'Contact Us': 'اتصل بنا',
          'Sign Out': 'تسجيل خروج',
          'Rating': 'التقييمات',
          'Ratings': 'التقييم',
          'Rated by': 'تم التقييم من ',
          'Details': 'التفاصيل',
          'Rate': 'تقييم',
          'Person': 'شخص',
          'General': 'إعدادات عامة',
          'Complaints List': 'قائمة الشكاوي المقدمة',
          'Terms Of Use': 'شروط الاستخدام',
          'Privacy Policy': 'سياسة الخصوصية',
          'Rate The App': 'قيم التطبيق',
          'About The App': 'نبذة عن التطبيق',
          'Add balance in case of payment to the owner of the roof':
              'إضافة رصيد في حال لدفع لصاحب السطحة',
          'Add Credit': 'اضافة رصيد',
          'Previous Operations': 'العمليات السابقة',
          'Deposit': 'إيداع',
          'Other Offer': 'عرض آخر',
          'Home': 'الرئيسية',
          'Order': 'الطلبات',
          'Profile': 'حسابي',
          'Next': 'التالي',
          'Do you want to cancel the order': 'هل تريد الغاء الطلب',
          'Yes': 'نعم',
          'Cancel': 'الغاء',
          'KM': 'كم',
          'Time': 'الوقت',
          'Call': 'اتصال',
          'Resend': 'إعادة الارسال',
          'Message': 'رسالة',
          'The Order': 'الطلب',
          'Total Price': 'إجمالي السعر ',
          'Order Cancel': 'الغاء الطلب',
          'Vehicle ID': 'رقم السيارة ',
          'Search': 'البحث',
          'Best': 'الأفضل',
          'The Offers': 'العروض',
          'Users': 'المستخدمون',
          'Vehicles': 'سطحات',
          'New Orders': 'طلبات جديدة',
          'Underway': 'قيد التنفيذ',
          'Completed': 'تم بنجاح',
          'Canceled': 'ملغية',
          'Reject': 'رفض',
          'Total Balance': 'الرصيد الحالي',
          'Enter the 4 digit code': 'أدخل رمز 4 أرقام',
          'Pending': 'قيد الانتظار',
          'How do I work in Ahtezam': 'كيف أعمل في احتزم',
          'surface for large cars': 'سطحة لسيارات الكبيرة',
          'Flatbed for sports cars (hydraulic)':
              'سطحة لسيارات الرياضية (هيدروليك)',
          'plain surface': 'سطحة عادي',
          'Quality': 'الجودة',
          'Treatment': 'المعاملة',
          'Cleanliness': 'النظافة',
          'Service': 'الخدمة',
          'Lighting': 'الاضاءة',
          'Confirm user place': 'وصلت مكان الانطلاق',
          'Add a comment': 'إضافة تعليق',
          'Evaluation': 'تقييم',
          'Notifications': 'الاشعارات',
          'Surface type': 'نوع السطحة',
          'Locate on map': 'حدد على الخريطة',
          'Something went wrong': 'حدث خطا ما ',
          'you didn\'t add any element': 'لم تقم بإضافة أي عنصر',
          'No Element Found': 'لم يتم العثور على عنصر',
          'There are no ratings': 'لا توجد تقييمات',
          'No one has rated this driver yet': 'لم يقم اي شخص بتقييم هذا السائق',
          'seconds ago': 'منذ ثواني',
          'minutes ago': 'منذ دقائق',
          'hours ago': 'منذ ساعات',
          'days ago': 'منذ أيام',
          'weeks ago': 'منذ أسابيع',
          'Send Order': 'ارسال الطلب',
          'Welcome': 'مرحباً بك',
          'Check Out': 'الدفعً',
          'Are you sure to pay': 'هل انت متاكد من الدفع عبر',
          'There are no chats': 'لا يوجد أي دردشات حاليا',
          'There are no orders': 'لا يوجد طلبات',
          'No Offer Found': 'لم يتم العثور على أي عرض',
          'No Notification Found': 'لم يتم العثور على أي إشعار',
          'No Chat Found': 'لم يتم العثور على أي دردشة',
          'No Message Found': 'لم يتم العثور على رسالة',
          'Enter the address': 'ادخل العنوان ',
          'ago': 'منذ',
          'seconds': 'ثانية',
          'hours': 'ساعة',
          'weeks': 'اسبوع',
          'days': 'يوم',
          'minutes': 'دقيقة',
          'Driver location': 'موقع السائق',
          'My location': 'موقعي',
          'Target': 'الهدف',
          'Current driver location': 'موقع السائق الحالي',
        },
        'en': {
          'Sign In': 'Sign In',
          'Register': 'Register',
          'Promotional text': 'Promotional text',
          'New Account': 'New Account',
          'Guest': 'Guest',
          'Forget Password': 'Forget Password',
          'Full Name': 'Full Name',
          'Gmail': 'Gmail',
          'Password': 'Password',
          'Mobile': 'Mobile',
          'Agree to privacy and terms': 'Agree to privacy and terms',
          'Chats': 'Chats',
          'Typing': 'Typing',
          'Offers': 'Offers',
          'Offer Details': 'Offer Details',
          'Vehicle Location': 'Vehicle Location',
          'From': 'From',
          'To': 'To',
          'SAR': 'SAR',
          'Send Offer': 'Send Offer',
          'Accepting Offer': 'Accepting Offer',
          'Delivery Price': 'Delivery Price',
          'Vehicle Order': 'Vehicle Order',
          'Service Price': 'Service Price',
          'Request completed successfully': 'Request completed successfully',
          'search on a vehicle in the area': 'search on a vehicle in the area',
          'Current Password': 'Current Password',
          'Create New Password': 'Create New Password',
          'New Password': 'New Password',
          'Password Confirmation': 'Password Confirmation',
          'Update': 'Update',
          'Update Information': 'Update Information',
          'Save': 'Save',
          'Favorite': 'Favorite',
          'Help': 'Help',
          'Wallet': 'Wallet',
          'Write what help you need': 'Write what help you need',
          'Common Questions': 'Common Questions',
          'Send': 'Send',
          'Share': 'Share',
          'Change Password': 'Change Password',
          'Setting': 'Setting',
          'Coupon': 'Coupon',
          'Terms and Conditions': 'Terms and Conditions',
          'Contact Us': 'Contact Us',
          'Sign Out': 'Sign Out',
          'Ratings': 'Ratings',
          'Rating': 'Rating',
          'Rated by': 'Rated by',
          'Person': 'Person',
          'General': 'General',
          'Complaints List': 'Complaints List',
          'Terms Of Use': 'Terms Of Use',
          'Privacy Policy': 'Privacy Policy',
          'Rate The App': 'Rate The App',
          'About The App': 'About The App',
          'Total Balance': 'Total Balance',
          'Add balance in case of payment to the owner of the roof':
              'Add balance in case of payment to the owner of the roof',
          'Add Credit': 'Add Credit',
          'Previous Operations': 'Previous Operations',
          'Deposit': 'Deposit',
          'Other Offer': 'Other Offer',
          'Home': 'Home',
          'Order': 'Order',
          'Profile': 'Profile',
          'Next': 'Next',
          'Do you want to cancel the order': 'Do you want to cancel the order',
          'Yes': 'Yes',
          'Cancel': 'Cancel',
          'KM': 'KM',
          'Time': 'Time',
          'Call': 'Call',
          'Message': 'Message',
          'The Order': 'The Order',
          'Total Price': 'Total Price',
          'Order Cancel': 'Order Cancel',
          'Vehicle ID': 'Vehicle ID',
          'Search': 'Search',
          'Best': 'Best',
          'The Offers': 'Offers',
          'Users': 'Users',
          'Vehicles': 'Vehicles',
          'New Orders': 'New Orders',
          'Underway': 'Underway',
          'Completed': 'Completed',
          'Canceled': 'Canceled',
          'Resend': 'Resend',
          'Send Code': 'Send Code',
          'Verified': 'Verified',
          'Pending': 'Pending',
          'How do I work in Ahtezam': 'How do I work in Ahtezam',
          'Enter the 4 digit code': 'Enter the 4 digit code',
          'surface for large cars': 'surface for large cars',
          'Flatbed for sports cars (hydraulic)':
              'Flatbed for sports cars (hydraulic)',
          'plain surface': 'plain surface',
          'Quality': 'Quality',
          'Treatment': 'Treatment',
          'Cleanliness': 'Cleanliness',
          'Service': 'Service',
          'Lighting': 'Lighting',
          'Add a comment': 'Add a comment',
          'Evaluation': 'Evaluation',
          'Notifications': 'Notifications',
          'Surface type': 'Surface type',
          'Locate on map': 'Locate on map',
          'Rate': 'Rate',
          'Details': 'Details',
          'Confirm user place': 'Confirm user place',
          'Something went wrong': 'Something went wrong',
          'you didn\'t add any element': 'you didn\'t add any element',
          'No Element Found': 'No Element Found',
          'There are no ratings': 'There are no ratings',
          'No one has rated this driver yet':
              'No one has rated this driver yet',
          'seconds ago': 'seconds ago',
          'minutes ago': 'minutes ago',
          'hours ago': 'hours ago',
          'days ago': 'days ago',
          'weeks ago': 'weeks ago',
          'Send Order': 'Send Order',
          'Reject': 'Reject',
          'Welcome': 'Welcome',
          'Check Out': 'Check Out',
          'Are you sure to pay': 'Are you sure to pay',
          'There are no orders': 'There are no orders',
          'There are no chats': 'There are no chats',
          'No Offer Found': 'No Offer Found',
          'No Notification Found': 'No Notification Found',
          'No Chat Found': 'No Chat Found',
          'No Message Found': 'No Message Found',
          'Enter the address': 'Enter the address',
          'ago': 'ago',
          'seconds': 'seconds',
          'hours': 'hours',
          'weeks': 'weeks',
          'days': 'days',
          'minutes': 'minutes',
          'Driver location': 'Driver location',
          'My location': 'My location',
          'Target': 'Target',
          // 'Target': 'Target',
          'Current driver location': 'Current driver location',
        },
      };
}
